### ISSUE TITLE
Big problems

### ISSUE THREAD

**Issue by steto123** [jrjfeath/Featherstone_Labs_Suite#5]
So i can not run the program using win 11 -> invalid directory (i will make a run for a crest xyz file= and the update do not work

in wsl2 the update clean my home directory with all installed programs. So many thanks for this.

I hope you can help to become the program running without destroying any system.

Thank you

**Comment by steto123** [comment]
Many thanks for your help.  I won't be back in the office, where the machine in question is located, until Friday. I will then test the patch and report back to you immediately.
Many thanks

**Comment by steto123** [comment]
I have freshly clones the repository  to my wsl2 and now i have the following error:

python3 Launcher.py
Traceback (most recent call last):
  File "/home/steffen/Featherstone_Labs_Suite/Launcher.py", line 39, in <module>
    from Launch.Launch_PyQt import main
  File "/home/steffen/Featherstone_Labs_Suite/Launch/Launch_PyQt.py", line 126
    self.ui.Console.setPlainText(f'Unable to access github, requests error: {repo['error']}')
                                                                                   ^^^^^
SyntaxError: f-string: unmatched '['



The same error is on windows

Sincerly
Steffen

**Comment by steto123** [comment]
I have change line 126 to the following 

self.ui.Console.setPlainText(f"Unable to access github, requests error: {repo['error']}")

and now it starts. But the Invalid directory error is not vanished. 
![Screenshot 2024-06-21 095042](https://github.com/jrjfeath/Featherstone_Labs_Suite/assets/27443089/4230f743-f237-4874-908d-ae43be36116b)

the same in wsl2

**Comment by steto123** [comment]
Did you have a solution for this error?

**Comment by jrjfeath** [comment]
Apologies I missed your previous email. I have now fixed the issue, please let me know if you run into any further issues. I plan to do a rewrite of the code this fall as it is a mess from various people contributing and needs to be optimized.

**Comment by steto123** [comment]
Hello and many thanks for your help,

i have cloned the repo again and now i have some more errors:

(base) PS E:\github\Featherstone_Labs_Suite> python launcher.py
Traceback (most recent call last):
  File "E:\github\Featherstone_Labs_Suite\launcher.py", line 39, in <module>
    from Launch.Launch_PyQt import main
  File "E:\github\Featherstone_Labs_Suite\Launch\Launch_PyQt.py", line 11, in <module>
    from .GUI_Triggered import GUI_Calls
  File "E:\github\Featherstone_Labs_Suite\Launch\GUI_Triggered.py", line 12, in <module>
    from Scripts.Temperature_Analysis import analyze_temperature
  File "E:\github\Featherstone_Labs_Suite\Scripts\Temperature_Analysis.py", line 5, in <module>
    from thermoanalysis.QCData import QCData
ModuleNotFoundError: No module named 'thermoanalysis'



sincerly 

St. Thomas


ps: this errors are the some in windows shell, in my anaconda base environment and in my ubuntu shell (wsl 2).  previously the launcher has started without errors.

**Comment by jrjfeath** [comment]
I had replaced old code with a new package, I've added it to the install script, so it should prompt you to install 'thermoanalysis' on launch now.

**Comment by jrjfeath** [comment]
All issues seem resolved.
